type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$"]

include_lines: ['^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}( [+-]\d{4})? [0-9A-Za-z]{6}-[0-9A-Za-z]{6}-[0-9A-Za-z]{2} (<=|=>|->|>>|==|\*\*)']
